[package]
name = "c-call"
version = "0.1.0"
authors = ["Taufik Rama <achmad.ramadhan@tokopedia.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
