[package]
authors = ["Taufik Rama <achmad.ramadhan@tokopedia.com>"]
edition = "2018"
name = "c-call"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.57.0"
